
// This file is auto-generated by generateApiHooks.js. Do not edit manually.
// To regenerate, run 'npm run gen:api:client' or 'npm run dev'.
import { useQuery, useMutation } from '@tanstack/react-query';

// --- API Client Configuration ---
const API_BASE_URL = import.meta.env.VITE_API_BASE_URL || 'https://zettanix.in';

/**
 * A generic API client that handles different content types.
 * @param {string} method HTTP method (e.g., 'get', 'post')
 * @param {string} path API endpoint path
 * @param {any} data Request body data
 * @param {string} contentType The Content-Type header value
 */
async function apiClient(method, path, data = null, contentType = 'application/json') {
  const url = `${API_BASE_URL}${path}`;
  const options = {
    method: method.toUpperCase(),
  };

  if (data) {
    if (contentType === 'multipart/form-data') {
      options.body = data; // Assumes data is already a FormData object
    } else {
      options.headers = {
        'Content-Type': contentType,
      };
      options.body = JSON.stringify(data);
    }
  }

  const response = await fetch(url, options);

  if (!response.ok) {
    const error = new Error(`API request failed with status ${response.status}`);
    try {
      error.response = await response.json();
    } catch (e) {
      error.response = await response.text();
    }
    throw error;
  }

  if (response.headers.get('content-type')?.includes('application/json')) {
    return response.json();
  }
  
  return response.text();
}

// --- Generated Models & Types ---
/**
 * @typedef {object} AnalysisStatus
 */
/**
 * @typedef {object} Body_upload_resume_api_v1_resumes_post
 * @property {string} file
 * @property {object} callback_url
 */
/**
 * @typedef {object} HTTPValidationError
 * @property {ValidationError[]} detail
 */
/**
 * @typedef {object} HealthModel
 * @property {string} status
 * @property {string} service
 * @property {string} version
 * @property {string} timestamp
 */
/**
 * @typedef {object} HealthZModel
 * @property {string} status
 */
/**
 * @typedef {object} ResumeAnalysis
 * @property {integer} id
 * @property {AnalysisStatus} status
 * @property {object} analysis
 * @property {object} error_message
 */
/**
 * @typedef {object} ResumeRead
 * @property {object} filename
 * @property {object} callback_url
 * @property {integer} id
 * @property {object} content_type
 * @property {object} file_url
 * @property {AnalysisStatus} status
 * @property {object} ai_model
 * @property {string} created_at
 * @property {string} updated_at
 */
/**
 * @typedef {object} RootModel
 * @property {string} message
 * @property {string} version
 * @property {string} docs
 * @property {string} health
 */
/**
 * @typedef {object} ValidationError
 * @property {object[]} loc
 * @property {string} msg
 * @property {string} type
 */
/**
 * @typedef {object} BehavioralEvaluationRequest
 * @property {string} question
 * @property {string} response
 */
/**
 * @typedef {object} BehavioralEvaluationResult
 * @property {string} evaluation
 */
/**
 * @typedef {object} BehavioralQuestionsResponse
 * @property {string[]} questions
 */
/**
 * @typedef {object} BehavioralRequest
 * @property {string} skills
 * @property {string} level
 * @property {string} job_role
 * @property {string} test_type
 * @property {string} company
 */
/**
 * @typedef {object} ChallengeRequest
 * @property {string} skills
 * @property {string} job_role
 * @property {string} job_description
 * @property {string} level
 * @property {string} company
 */
/**
 * @typedef {object} ChallengeResponse
 * @property {string} challenge
 */
/**
 * @typedef {object} CodeEvaluationRequest
 * @property {string} challenge
 * @property {string} solution
 */
/**
 * @typedef {object} CodeEvaluationResponse
 * @property {string} evaluation
 */
/**
 * @typedef {object} CompanyAnswerEvaluationResponse
 * @property {string} evaluation
 */
/**
 * @typedef {object} CompanyAnswerRequest
 * @property {string} company
 * @property {string} round
 * @property {string} question
 * @property {string} answer
 * @property {string} type
 * @property {string} role
 * @property {string} experience
 */
/**
 * @typedef {object} CompanyQuestionRequest
 * @property {string} company
 * @property {string} round
 * @property {string} focus
 * @property {string} description
 * @property {string} type
 * @property {string} role
 * @property {string} experience
 */
/**
 * @typedef {object} CompanyQuestionResponse
 * @property {string} question
 */
/**
 * @typedef {object} EvaluateRequest
 * @property {Question[]} questions
 * @property {string[]} answers
 */
/**
 * @typedef {object} EvaluateResponse
 * @property {integer} score
 * @property {integer} total
 * @property {boolean} passed
 * @property {number} time_taken
 * @property {EvaluationResult[]} results
 */
/**
 * @typedef {object} EvaluationResult
 * @property {string} question
 * @property {string} user_answer
 * @property {string} correct_answer
 * @property {boolean} is_correct
 */
/**
 * @typedef {object} GenerateResponse
 * @property {integer} seed
 * @property {Question[]} questions
 */
/**
 * @typedef {object} InterviewPDFRequest
 * @property {number} final_score
 * @property {object} scores
 * @property {object} section_times
 * @property {object} recommendations
 * @property {string} skills
 * @property {string} test_type
 */
/**
 * @typedef {object} InterviewPDFResponse
 * @property {string} pdf
 */
/**
 * @typedef {object} MCQQuestion
 * @property {string} question
 * @property {string[]} options
 * @property {string} answer
 */
/**
 * @typedef {object} MCQRequest
 * @property {string} skills
 * @property {string} level
 * @property {string} job_role
 * @property {string} job_description
 * @property {string} test_type
 */
/**
 * @typedef {object} MCQResponse
 * @property {MCQQuestion[]} questions
 */
/**
 * @typedef {object} PerformanceGapsRequest
 * @property {object} scores
 * @property {string} feedback
 */
/**
 * @typedef {object} PerformanceGapsResponse
 * @property {object} analysis
 */
/**
 * @typedef {object} Question
 * @property {string} question
 * @property {string} answer
 */
/**
 * @typedef {object} ReportRequest
 * @property {object[]} jobs
 * @property {object} analysis
 */
/**
 * @typedef {object} ReportResponse
 * @property {object} report
 */
/**
 * @typedef {object} SkillRecommendationsRequest
 * @property {string} skills
 * @property {object} scores
 */
/**
 * @typedef {object} SkillRecommendationsResponse
 * @property {object} recommendations
 */
/**
 * @typedef {object} WritingEvaluationRequest
 * @property {string} prompt
 * @property {string} response
 */
/**
 * @typedef {object} WritingEvaluationResult
 * @property {string} evaluation
 */
/**
 * @typedef {object} WritingPromptResponse
 * @property {string} prompt
 */
/**
 * @typedef {object} WritingRequest
 * @property {string} skills
 * @property {string} job_role
 * @property {string} test_type
 */
/**
 * @typedef {object} LoginRequest
 * @property {string} email
 * @property {string} password
 */
/**
 * @typedef {object} TokenIntrospection
 * @property {boolean} active
 * @property {object} sub
 * @property {object} exp
 * @property {object} roles
 */
/**
 * @typedef {object} TokenPair
 * @property {string} access_token
 * @property {string} refresh_token
 * @property {string} token_type
 */
/**
 * @typedef {object} UserCreate
 * @property {string} email
 * @property {object} name
 * @property {object} phone
 * @property {object} is_active
 * @property {object} is_superuser
 * @property {string} password
 */
/**
 * @typedef {object} UserOut
 * @property {string} email
 * @property {object} name
 * @property {object} phone
 * @property {object} is_active
 * @property {object} is_superuser
 * @property {integer} id
 * @property {string[]} roles
 */
/**
 * @typedef {object} CompanyCreate
 * @property {string} name
 * @property {object} website
 * @property {object} domain
 * @property {object} industry
 * @property {object} size_range
 * @property {object} hq_country
 * @property {object} hq_city
 * @property {object} founded_year
 * @property {object} description
 */
/**
 * @typedef {object} CompanyOut
 * @property {string} name
 * @property {object} website
 * @property {object} domain
 * @property {object} industry
 * @property {object} size_range
 * @property {object} hq_country
 * @property {object} hq_city
 * @property {object} founded_year
 * @property {object} description
 * @property {integer} id
 * @property {string} created_at
 * @property {string} updated_at
 */
/**
 * @typedef {object} CompanyUpdate
 * @property {string} name
 * @property {object} website
 * @property {object} domain
 * @property {object} industry
 * @property {object} size_range
 * @property {object} hq_country
 * @property {object} hq_city
 * @property {object} founded_year
 * @property {object} description
 */
/**
 * @typedef {object} EmploymentType
 */
/**
 * @typedef {object} JobCreate
 * @property {string} title
 * @property {string} description
 * @property {object} company_name
 * @property {object} company_website
 * @property {object} company_id
 * @property {EmploymentType} employment_type
 * @property {WorkType} work_type
 * @property {object} seniority_level
 * @property {object} country
 * @property {object} state
 * @property {object} city
 * @property {object} address
 * @property {object} min_experience_years
 * @property {object} max_experience_years
 * @property {object} skills
 * @property {object} tags
 * @property {object} salary_currency
 * @property {object} salary_min
 * @property {object} salary_max
 * @property {SalaryPeriod} salary_period
 * @property {object} benefits
 * @property {boolean} visa_sponsorship
 * @property {boolean} relocation_assistance
 * @property {object} application_url
 * @property {object} application_email
 * @property {JobStatus} status
 */
/**
 * @typedef {object} JobOut
 * @property {string} title
 * @property {string} description
 * @property {object} company_name
 * @property {object} company_website
 * @property {object} company_id
 * @property {EmploymentType} employment_type
 * @property {WorkType} work_type
 * @property {object} seniority_level
 * @property {object} country
 * @property {object} state
 * @property {object} city
 * @property {object} address
 * @property {object} min_experience_years
 * @property {object} max_experience_years
 * @property {object} skills
 * @property {object} tags
 * @property {object} salary_currency
 * @property {object} salary_min
 * @property {object} salary_max
 * @property {SalaryPeriod} salary_period
 * @property {object} benefits
 * @property {boolean} visa_sponsorship
 * @property {boolean} relocation_assistance
 * @property {object} application_url
 * @property {object} application_email
 * @property {JobStatus} status
 * @property {integer} id
 * @property {string} posted_at
 * @property {string} updated_at
 * @property {boolean} is_deleted
 * @property {object} deleted_at
 * @property {object} company
 */
/**
 * @typedef {object} JobStatus
 */
/**
 * @typedef {object} JobUpdate
 * @property {string} title
 * @property {string} description
 * @property {object} company_name
 * @property {object} company_website
 * @property {object} company_id
 * @property {EmploymentType} employment_type
 * @property {WorkType} work_type
 * @property {object} seniority_level
 * @property {object} country
 * @property {object} state
 * @property {object} city
 * @property {object} address
 * @property {object} min_experience_years
 * @property {object} max_experience_years
 * @property {object} skills
 * @property {object} tags
 * @property {object} salary_currency
 * @property {object} salary_min
 * @property {object} salary_max
 * @property {SalaryPeriod} salary_period
 * @property {object} benefits
 * @property {boolean} visa_sponsorship
 * @property {boolean} relocation_assistance
 * @property {object} application_url
 * @property {object} application_email
 * @property {JobStatus} status
 */
/**
 * @typedef {object} SalaryPeriod
 */
/**
 * @typedef {object} SeniorityLevel
 */
/**
 * @typedef {object} WorkType
 */
/**
 * @typedef {object} CacheRefreshResponse
 * @property {boolean} success - Request success status
 * @property {string} message - Response message
 * @property {string} timestamp - Response timestamp
 */
/**
 * @typedef {object} NewsCategory
 */
/**
 * @typedef {object} NewsItem
 * @property {object} id
 * @property {string} title - News title
 * @property {object} description - News description
 * @property {string} url - News URL
 * @property {string} source_name - Source name
 * @property {NewsCategory} category - News category
 * @property {object} published_at - Publication date
 * @property {object} image_url - Image URL
 * @property {object} author - Author name
 * @property {object} relevance_score - Relevance score
 */
/**
 * @typedef {object} NewsResponse
 * @property {boolean} success - Request success status
 * @property {NewsItem[]} data - News items
 * @property {integer} count - Number of news items
 * @property {boolean} cached - Whether data is from cache
 * @property {string} timestamp - Response timestamp
 */
/**
 * @typedef {object} NewsSummaryResponse
 * @property {boolean} success - Request success status
 * @property {object} data - Summary data
 * @property {string} timestamp - Response timestamp
 */

// --- Generated React Query Hooks ---

/**
 * @description Hook for /resumes/api/v1/resumes [GET]
 * @returns {import('@tanstack/react-query').QueryResult<ResumeRead[]>}
 */
export const listResumesApiV1ResumesGet = (options) => {
  const queryKey = ['list_resumes_api_v1_resumes_get'];
  return useQuery({
    queryKey,
    queryFn: () => apiClient('get', '/resumes/api/v1/resumes'),
    ...options,
  });
};

/**
 * @description Hook for /resumes/api/v1/resumes [POST]
 * @param {Body_upload_resume_api_v1_resumes_post} data The request body based on the OpenAPI specification.
 * @returns {import('@tanstack/react-query').MutationResult<ResumeRead, unknown, Body_upload_resume_api_v1_resumes_post>}
 */
export const uploadResumeApiV1ResumesPost = (options) => {
  return useMutation({
    mutationFn: (data) => apiClient('post', '/resumes/api/v1/resumes', data, 'multipart/form-data'),
    ...options,
  });
};

/**
 * @description Hook for /resumes/api/v1/resumes/{resume_id} [GET]
 * @returns {import('@tanstack/react-query').QueryResult<ResumeRead>}
 */
export const getResumeApiV1Resumes_ResumeId_Get = (options) => {
  const resume_id = options?.resume_id;
  const queryKey = ['get_resume_api_v1_resumes__resume_id__get', resume_id];
  return useQuery({
    queryKey,
    queryFn: () => apiClient('get', `/resumes/api/v1/resumes/${resume_id}`),
    enabled: !!resume_id,
    ...options,
  });
};

/**
 * @description Hook for /resumes/api/v1/resumes/{resume_id} [DELETE]
 * @param {void} data The request body based on the OpenAPI specification.
 * @returns {import('@tanstack/react-query').MutationResult<object, unknown, void>}
 */
export const deleteResumeApiV1Resumes_ResumeId_Delete = (options) => {
  return useMutation({
    mutationFn: ({ resume_id, ...data }) => apiClient('delete', `/resumes/api/v1/resumes/${resume_id}`, data),
    ...options,
  });
};

/**
 * @description Hook for /resumes/api/v1/resumes/{resume_id}/analysis [GET]
 * @returns {import('@tanstack/react-query').QueryResult<ResumeAnalysis>}
 */
export const getAnalysisApiV1Resumes_ResumeId_AnalysisGet = (options) => {
  const resume_id = options?.resume_id;
  const queryKey = ['get_analysis_api_v1_resumes__resume_id__analysis_get', resume_id];
  return useQuery({
    queryKey,
    queryFn: () => apiClient('get', `/resumes/api/v1/resumes/${resume_id}/analysis`),
    enabled: !!resume_id,
    ...options,
  });
};

/**
 * @description Hook for /resumes/api/v1/resumes/{resume_id}/re-analyze [POST]
 * @param {void} data The request body based on the OpenAPI specification.
 * @returns {import('@tanstack/react-query').MutationResult<ResumeAnalysis, unknown, void>}
 */
export const reanalyzeApiV1Resumes_ResumeId_ReAnalyzePost = (options) => {
  return useMutation({
    mutationFn: ({ resume_id, ...data }) => apiClient('post', `/resumes/api/v1/resumes/${resume_id}/re-analyze`, data),
    ...options,
  });
};

/**
 * @description Hook for /resumes/api/v1/resumes/admin/all [GET]
 * @returns {import('@tanstack/react-query').QueryResult<ResumeRead[]>}
 */
export const adminListAllApiV1ResumesAdminAllGet = (options) => {
  const queryKey = ['admin_list_all_api_v1_resumes_admin_all_get'];
  return useQuery({
    queryKey,
    queryFn: () => apiClient('get', '/resumes/api/v1/resumes/admin/all'),
    ...options,
  });
};

/**
 * @description Hook for /resumes/ [GET]
 * @returns {import('@tanstack/react-query').QueryResult<RootModel>}
 */
export const resumeRoot_Get = (options) => {
  const queryKey = ['resume_root__get'];
  return useQuery({
    queryKey,
    queryFn: () => apiClient('get', '/resumes/'),
    ...options,
  });
};

/**
 * @description Hook for /resumes/health [GET]
 * @returns {import('@tanstack/react-query').QueryResult<HealthModel>}
 */
export const resumeHealthCheckHealthGet = (options) => {
  const queryKey = ['resume_health_check_health_get'];
  return useQuery({
    queryKey,
    queryFn: () => apiClient('get', '/resumes/health'),
    ...options,
  });
};

/**
 * @description Hook for /resumes/healthz [GET]
 * @returns {import('@tanstack/react-query').QueryResult<HealthZModel>}
 */
export const healthzHealthzGet = (options) => {
  const queryKey = ['healthz_healthz_get'];
  return useQuery({
    queryKey,
    queryFn: () => apiClient('get', '/resumes/healthz'),
    ...options,
  });
};

/**
 * @description Hook for /quiz/generate_aptitude [POST]
 * @param {void} data The request body based on the OpenAPI specification.
 * @returns {import('@tanstack/react-query').MutationResult<GenerateResponse, unknown, void>}
 */
export const generateQuestionsGenerateAptitudePost = (options) => {
  return useMutation({
    mutationFn: (data) => apiClient('post', '/quiz/generate_aptitude', data),
    ...options,
  });
};

/**
 * @description Hook for /quiz/evaluate_aptitude [POST]
 * @param {EvaluateRequest} data The request body based on the OpenAPI specification.
 * @returns {import('@tanstack/react-query').MutationResult<EvaluateResponse, unknown, EvaluateRequest>}
 */
export const evaluateAnswersEvaluateAptitudePost = (options) => {
  return useMutation({
    mutationFn: (data) => apiClient('post', '/quiz/evaluate_aptitude', data, 'application/json'),
    ...options,
  });
};

/**
 * @description Hook for /quiz/generate_challenge [POST]
 * @param {ChallengeRequest} data The request body based on the OpenAPI specification.
 * @returns {import('@tanstack/react-query').MutationResult<ChallengeResponse, unknown, ChallengeRequest>}
 */
export const generateRandomCodingChallengeGenerateChallengePost = (options) => {
  return useMutation({
    mutationFn: (data) => apiClient('post', '/quiz/generate_challenge', data, 'application/json'),
    ...options,
  });
};

/**
 * @description Hook for /quiz/evaluate_code [POST]
 * @param {CodeEvaluationRequest} data The request body based on the OpenAPI specification.
 * @returns {import('@tanstack/react-query').MutationResult<CodeEvaluationResponse, unknown, CodeEvaluationRequest>}
 */
export const evaluateCodeSolutionEvaluateCodePost = (options) => {
  return useMutation({
    mutationFn: (data) => apiClient('post', '/quiz/evaluate_code', data, 'application/json'),
    ...options,
  });
};

/**
 * @description Hook for /quiz/generate_mcq [POST]
 * @param {MCQRequest} data The request body based on the OpenAPI specification.
 * @returns {import('@tanstack/react-query').MutationResult<MCQResponse, unknown, MCQRequest>}
 */
export const generateMcqQuestionsGenerateMcqPost = (options) => {
  return useMutation({
    mutationFn: (data) => apiClient('post', '/quiz/generate_mcq', data, 'application/json'),
    ...options,
  });
};

/**
 * @description Hook for /quiz/generate_behavioral_questions [POST]
 * @param {BehavioralRequest} data The request body based on the OpenAPI specification.
 * @returns {import('@tanstack/react-query').MutationResult<BehavioralQuestionsResponse, unknown, BehavioralRequest>}
 */
export const generateBehavioralQuestionsGenerateBehavioralQuestionsPost = (options) => {
  return useMutation({
    mutationFn: (data) => apiClient('post', '/quiz/generate_behavioral_questions', data, 'application/json'),
    ...options,
  });
};

/**
 * @description Hook for /quiz/evaluate_behavioral [POST]
 * @param {BehavioralEvaluationRequest} data The request body based on the OpenAPI specification.
 * @returns {import('@tanstack/react-query').MutationResult<BehavioralEvaluationResult, unknown, BehavioralEvaluationRequest>}
 */
export const evaluateBehavioralResponseEvaluateBehavioralPost = (options) => {
  return useMutation({
    mutationFn: (data) => apiClient('post', '/quiz/evaluate_behavioral', data, 'application/json'),
    ...options,
  });
};

/**
 * @description Hook for /quiz/generate_writing_prompt [POST]
 * @param {WritingRequest} data The request body based on the OpenAPI specification.
 * @returns {import('@tanstack/react-query').MutationResult<WritingPromptResponse, unknown, WritingRequest>}
 */
export const generateWritingPromptGenerateWritingPromptPost = (options) => {
  return useMutation({
    mutationFn: (data) => apiClient('post', '/quiz/generate_writing_prompt', data, 'application/json'),
    ...options,
  });
};

/**
 * @description Hook for /quiz/evaluate_writing [POST]
 * @param {WritingEvaluationRequest} data The request body based on the OpenAPI specification.
 * @returns {import('@tanstack/react-query').MutationResult<WritingEvaluationResult, unknown, WritingEvaluationRequest>}
 */
export const evaluateWritingResponseEvaluateWritingPost = (options) => {
  return useMutation({
    mutationFn: (data) => apiClient('post', '/quiz/evaluate_writing', data, 'application/json'),
    ...options,
  });
};

/**
 * @description Hook for /quiz/analyze_performance_gaps [POST]
 * @param {PerformanceGapsRequest} data The request body based on the OpenAPI specification.
 * @returns {import('@tanstack/react-query').MutationResult<PerformanceGapsResponse, unknown, PerformanceGapsRequest>}
 */
export const analyzePerformanceGapsAnalyzePerformanceGapsPost = (options) => {
  return useMutation({
    mutationFn: (data) => apiClient('post', '/quiz/analyze_performance_gaps', data, 'application/json'),
    ...options,
  });
};

/**
 * @description Hook for /quiz/generate_skill_based_recommendations [POST]
 * @param {SkillRecommendationsRequest} data The request body based on the OpenAPI specification.
 * @returns {import('@tanstack/react-query').MutationResult<SkillRecommendationsResponse, unknown, SkillRecommendationsRequest>}
 */
export const generateSkillBasedRecommendationsGenerateSkillBasedRecommendationsPost = (options) => {
  return useMutation({
    mutationFn: (data) => apiClient('post', '/quiz/generate_skill_based_recommendations', data, 'application/json'),
    ...options,
  });
};

/**
 * @description Hook for /quiz/download-report [POST]
 * @param {ReportRequest} data The request body based on the OpenAPI specification.
 * @returns {import('@tanstack/react-query').MutationResult<ReportResponse, unknown, ReportRequest>}
 */
export const downloadReportDownloadReportPost = (options) => {
  return useMutation({
    mutationFn: (data) => apiClient('post', '/quiz/download-report', data, 'application/json'),
    ...options,
  });
};

/**
 * @description Hook for /quiz/generate_interview_pdf [POST]
 * @param {InterviewPDFRequest} data The request body based on the OpenAPI specification.
 * @returns {import('@tanstack/react-query').MutationResult<InterviewPDFResponse, unknown, InterviewPDFRequest>}
 */
export const generateInterviewPdfGenerateInterviewPdfPost = (options) => {
  return useMutation({
    mutationFn: (data) => apiClient('post', '/quiz/generate_interview_pdf', data, 'application/json'),
    ...options,
  });
};

/**
 * @description Hook for /quiz/company-rounds [GET]
 * @returns {import('@tanstack/react-query').QueryResult<object>}
 */
export const getCompanyRoundsCompanyRoundsGet = (options) => {
  const queryKey = ['get_company_rounds_company_rounds_get'];
  return useQuery({
    queryKey,
    queryFn: () => apiClient('get', '/quiz/company-rounds'),
    ...options,
  });
};

/**
 * @description Hook for /quiz/generate_company_question [POST]
 * @param {CompanyQuestionRequest} data The request body based on the OpenAPI specification.
 * @returns {import('@tanstack/react-query').MutationResult<CompanyQuestionResponse, unknown, CompanyQuestionRequest>}
 */
export const generateCompanyQuestionGenerateCompanyQuestionPost = (options) => {
  return useMutation({
    mutationFn: (data) => apiClient('post', '/quiz/generate_company_question', data, 'application/json'),
    ...options,
  });
};

/**
 * @description Hook for /quiz/evaluate_company_answer [POST]
 * @param {CompanyAnswerRequest} data The request body based on the OpenAPI specification.
 * @returns {import('@tanstack/react-query').MutationResult<CompanyAnswerEvaluationResponse, unknown, CompanyAnswerRequest>}
 */
export const evaluateCompanyAnswerEvaluateCompanyAnswerPost = (options) => {
  return useMutation({
    mutationFn: (data) => apiClient('post', '/quiz/evaluate_company_answer', data, 'application/json'),
    ...options,
  });
};

/**
 * @description Hook for /quiz/ [GET]
 * @returns {import('@tanstack/react-query').QueryResult<object>}
 */
export const quizRoot_Get = (options) => {
  const queryKey = ['quiz_root__get'];
  return useQuery({
    queryKey,
    queryFn: () => apiClient('get', '/quiz/'),
    ...options,
  });
};

/**
 * @description Hook for /quiz/health [GET]
 * @returns {import('@tanstack/react-query').QueryResult<object>}
 */
export const QuizHealthCheckHealthGet = (options) => {
  const queryKey = ['Quiz_health_check_health_get'];
  return useQuery({
    queryKey,
    queryFn: () => apiClient('get', '/quiz/health'),
    ...options,
  });
};

/**
 * @description Hook for /auth/register [POST]
 * @param {UserCreate} data The request body based on the OpenAPI specification.
 * @returns {import('@tanstack/react-query').MutationResult<UserOut, unknown, UserCreate>}
 */
export const registerRegisterPost = (options) => {
  return useMutation({
    mutationFn: (data) => apiClient('post', '/auth/register', data, 'application/json'),
    ...options,
  });
};

/**
 * @description Hook for /auth/login [POST]
 * @param {LoginRequest} data The request body based on the OpenAPI specification.
 * @returns {import('@tanstack/react-query').MutationResult<TokenPair, unknown, LoginRequest>}
 */
export const loginLoginPost = (options) => {
  return useMutation({
    mutationFn: (data) => apiClient('post', '/auth/login', data, 'application/json'),
    ...options,
  });
};

/**
 * @description Hook for /auth/refresh [POST]
 * @param {void} data The request body based on the OpenAPI specification.
 * @returns {import('@tanstack/react-query').MutationResult<TokenPair, unknown, void>}
 */
export const refreshTokenRefreshPost = (options) => {
  return useMutation({
    mutationFn: (data) => apiClient('post', '/auth/refresh', data),
    ...options,
  });
};

/**
 * @description Hook for /auth/me [GET]
 * @returns {import('@tanstack/react-query').QueryResult<UserOut>}
 */
export const meMeGet = (options) => {
  const queryKey = ['me_me_get'];
  return useQuery({
    queryKey,
    queryFn: () => apiClient('get', '/auth/me'),
    ...options,
  });
};

/**
 * @description Hook for /auth/introspect [POST]
 * @param {void} data The request body based on the OpenAPI specification.
 * @returns {import('@tanstack/react-query').MutationResult<TokenIntrospection, unknown, void>}
 */
export const introspectIntrospectPost = (options) => {
  return useMutation({
    mutationFn: (data) => apiClient('post', '/auth/introspect', data),
    ...options,
  });
};

/**
 * @description Hook for /auth/ [GET]
 * @returns {import('@tanstack/react-query').QueryResult<object>}
 */
export const authRoot_Get = (options) => {
  const queryKey = ['auth_root__get'];
  return useQuery({
    queryKey,
    queryFn: () => apiClient('get', '/auth/'),
    ...options,
  });
};

/**
 * @description Hook for /auth/health [GET]
 * @returns {import('@tanstack/react-query').QueryResult<object>}
 */
export const authHealthCheckHealthGet = (options) => {
  const queryKey = ['auth_health_check_health_get'];
  return useQuery({
    queryKey,
    queryFn: () => apiClient('get', '/auth/health'),
    ...options,
  });
};

/**
 * @description Hook for /jobs/api/v1/companies [GET]
 * @returns {import('@tanstack/react-query').QueryResult<CompanyOut[]>}
 */
export const listCompaniesApiV1CompaniesGet = (options) => {
  const queryKey = ['list_companies_api_v1_companies_get'];
  return useQuery({
    queryKey,
    queryFn: () => apiClient('get', '/jobs/api/v1/companies'),
    ...options,
  });
};

/**
 * @description Hook for /jobs/api/v1/companies [POST]
 * @param {CompanyCreate} data The request body based on the OpenAPI specification.
 * @returns {import('@tanstack/react-query').MutationResult<CompanyOut, unknown, CompanyCreate>}
 */
export const createCompanyApiV1CompaniesPost = (options) => {
  return useMutation({
    mutationFn: (data) => apiClient('post', '/jobs/api/v1/companies', data, 'application/json'),
    ...options,
  });
};

/**
 * @description Hook for /jobs/api/v1/companies/{company_id} [GET]
 * @returns {import('@tanstack/react-query').QueryResult<CompanyOut>}
 */
export const getCompanyApiV1Companies_CompanyId_Get = (options) => {
  const company_id = options?.company_id;
  const queryKey = ['get_company_api_v1_companies__company_id__get', company_id];
  return useQuery({
    queryKey,
    queryFn: () => apiClient('get', `/jobs/api/v1/companies/${company_id}`),
    enabled: !!company_id,
    ...options,
  });
};

/**
 * @description Hook for /jobs/api/v1/companies/{company_id} [PUT]
 * @param {CompanyUpdate} data The request body based on the OpenAPI specification.
 * @returns {import('@tanstack/react-query').MutationResult<CompanyOut, unknown, CompanyUpdate>}
 */
export const updateCompanyApiV1Companies_CompanyId_Put = (options) => {
  return useMutation({
    mutationFn: ({ company_id, ...data }) => apiClient('put', `/jobs/api/v1/companies/${company_id}`, data, 'application/json'),
    ...options,
  });
};

/**
 * @description Hook for /jobs/api/v1/companies/{company_id} [DELETE]
 * @param {void} data The request body based on the OpenAPI specification.
 * @returns {import('@tanstack/react-query').MutationResult<HTTPValidationError, unknown, void>}
 */
export const deleteCompanyApiV1Companies_CompanyId_Delete = (options) => {
  return useMutation({
    mutationFn: ({ company_id, ...data }) => apiClient('delete', `/jobs/api/v1/companies/${company_id}`, data),
    ...options,
  });
};

/**
 * @description Hook for /jobs/api/v1/jobs [GET]
 * @returns {import('@tanstack/react-query').QueryResult<JobOut[]>}
 */
export const listJobsApiV1JobsGet = (options) => {
  const queryKey = ['list_jobs_api_v1_jobs_get'];
  return useQuery({
    queryKey,
    queryFn: () => apiClient('get', '/jobs/api/v1/jobs'),
    ...options,
  });
};

/**
 * @description Hook for /jobs/api/v1/jobs [POST]
 * @param {JobCreate} data The request body based on the OpenAPI specification.
 * @returns {import('@tanstack/react-query').MutationResult<JobOut, unknown, JobCreate>}
 */
export const createJobApiV1JobsPost = (options) => {
  return useMutation({
    mutationFn: (data) => apiClient('post', '/jobs/api/v1/jobs', data, 'application/json'),
    ...options,
  });
};

/**
 * @description Hook for /jobs/api/v1/jobs/{job_id} [GET]
 * @returns {import('@tanstack/react-query').QueryResult<JobOut>}
 */
export const getJobApiV1Jobs_JobId_Get = (options) => {
  const job_id = options?.job_id;
  const queryKey = ['get_job_api_v1_jobs__job_id__get', job_id];
  return useQuery({
    queryKey,
    queryFn: () => apiClient('get', `/jobs/api/v1/jobs/${job_id}`),
    enabled: !!job_id,
    ...options,
  });
};

/**
 * @description Hook for /jobs/api/v1/jobs/{job_id} [PUT]
 * @param {JobUpdate} data The request body based on the OpenAPI specification.
 * @returns {import('@tanstack/react-query').MutationResult<JobOut, unknown, JobUpdate>}
 */
export const updateJobApiV1Jobs_JobId_Put = (options) => {
  return useMutation({
    mutationFn: ({ job_id, ...data }) => apiClient('put', `/jobs/api/v1/jobs/${job_id}`, data, 'application/json'),
    ...options,
  });
};

/**
 * @description Hook for /jobs/api/v1/jobs/{job_id} [DELETE]
 * @param {void} data The request body based on the OpenAPI specification.
 * @returns {import('@tanstack/react-query').MutationResult<HTTPValidationError, unknown, void>}
 */
export const deleteJobApiV1Jobs_JobId_Delete = (options) => {
  return useMutation({
    mutationFn: ({ job_id, ...data }) => apiClient('delete', `/jobs/api/v1/jobs/${job_id}`, data),
    ...options,
  });
};

/**
 * @description Hook for /jobs/api/v1/jobs/{job_id}/restore [POST]
 * @param {void} data The request body based on the OpenAPI specification.
 * @returns {import('@tanstack/react-query').MutationResult<JobOut, unknown, void>}
 */
export const restoreJobApiV1Jobs_JobId_RestorePost = (options) => {
  return useMutation({
    mutationFn: ({ job_id, ...data }) => apiClient('post', `/jobs/api/v1/jobs/${job_id}/restore`, data),
    ...options,
  });
};

/**
 * @description Hook for /jobs/api/v1/jobs/{job_id}/audits [GET]
 * @returns {import('@tanstack/react-query').QueryResult<object[]>}
 */
export const listJobAuditsApiV1Jobs_JobId_AuditsGet = (options) => {
  const job_id = options?.job_id;
  const queryKey = ['list_job_audits_api_v1_jobs__job_id__audits_get', job_id];
  return useQuery({
    queryKey,
    queryFn: () => apiClient('get', `/jobs/api/v1/jobs/${job_id}/audits`),
    enabled: !!job_id,
    ...options,
  });
};

/**
 * @description Hook for /jobs/api/v1/jobs/{job_id}/hard-delete [DELETE]
 * @param {void} data The request body based on the OpenAPI specification.
 * @returns {import('@tanstack/react-query').MutationResult<HTTPValidationError, unknown, void>}
 */
export const hardDeleteJobApiV1Jobs_JobId_HardDeleteDelete = (options) => {
  return useMutation({
    mutationFn: ({ job_id, ...data }) => apiClient('delete', `/jobs/api/v1/jobs/${job_id}/hard-delete`, data),
    ...options,
  });
};

/**
 * @description Hook for /jobs/api/v1/jobs/stats [GET]
 * @returns {import('@tanstack/react-query').QueryResult<object>}
 */
export const jobsStatsApiV1JobsStatsGet = (options) => {
  const queryKey = ['jobs_stats_api_v1_jobs_stats_get'];
  return useQuery({
    queryKey,
    queryFn: () => apiClient('get', '/jobs/api/v1/jobs/stats'),
    ...options,
  });
};

/**
 * @description Hook for /jobs/ [GET]
 * @returns {import('@tanstack/react-query').QueryResult<RootModel>}
 */
export const jobsRoot_Get = (options) => {
  const queryKey = ['jobs_root__get'];
  return useQuery({
    queryKey,
    queryFn: () => apiClient('get', '/jobs/'),
    ...options,
  });
};

/**
 * @description Hook for /jobs/health [GET]
 * @returns {import('@tanstack/react-query').QueryResult<HealthModel>}
 */
export const jobsHealthCheckHealthGet = (options) => {
  const queryKey = ['jobs_health_check_health_get'];
  return useQuery({
    queryKey,
    queryFn: () => apiClient('get', '/jobs/health'),
    ...options,
  });
};

/**
 * @description Hook for /jobs/healthz [GET]
 * @returns {import('@tanstack/react-query').QueryResult<HealthZModel>}
 */
export const jobsHealthzHealthzGet = (options) => {
  const queryKey = ['jobs_healthz_healthz_get'];
  return useQuery({
    queryKey,
    queryFn: () => apiClient('get', '/jobs/healthz'),
    ...options,
  });
};

/**
 * @description Hook for /news/api/v1/news/latest [GET]
 * @returns {import('@tanstack/react-query').QueryResult<NewsResponse>}
 */
export const getLatestNewsApiV1NewsLatestGet = (options) => {
  const queryKey = ['get_latest_news_api_v1_news_latest_get'];
  return useQuery({
    queryKey,
    queryFn: () => apiClient('get', '/news/api/v1/news/latest'),
    ...options,
  });
};

/**
 * @description Hook for /news/api/v1/news/category/{category} [GET]
 * @returns {import('@tanstack/react-query').QueryResult<NewsResponse>}
 */
export const getNewsByCategoryApiV1NewsCategory_Category_Get = (options) => {
  const queryKey = ['get_news_by_category_api_v1_news_category__category__get'];
  return useQuery({
    queryKey,
    queryFn: () => apiClient('get', '/news/api/v1/news/category/{category}'),
    ...options,
  });
};

/**
 * @description Hook for /news/api/v1/news/source/{source_name} [GET]
 * @returns {import('@tanstack/react-query').QueryResult<NewsResponse>}
 */
export const getNewsBySourceApiV1NewsSource_SourceName_Get = (options) => {
  const queryKey = ['get_news_by_source_api_v1_news_source__source_name__get'];
  return useQuery({
    queryKey,
    queryFn: () => apiClient('get', '/news/api/v1/news/source/{source_name}'),
    ...options,
  });
};

/**
 * @description Hook for /news/api/v1/news/search [GET]
 * @returns {import('@tanstack/react-query').QueryResult<NewsResponse>}
 */
export const searchNewsApiV1NewsSearchGet = (options) => {
  const queryKey = ['search_news_api_v1_news_search_get'];
  return useQuery({
    queryKey,
    queryFn: () => apiClient('get', '/news/api/v1/news/search'),
    ...options,
  });
};

/**
 * @description Hook for /news/api/v1/news/summary [GET]
 * @returns {import('@tanstack/react-query').QueryResult<NewsSummaryResponse>}
 */
export const getNewsSummaryApiV1NewsSummaryGet = (options) => {
  const queryKey = ['get_news_summary_api_v1_news_summary_get'];
  return useQuery({
    queryKey,
    queryFn: () => apiClient('get', '/news/api/v1/news/summary'),
    ...options,
  });
};

/**
 * @description Hook for /news/api/v1/news/refresh [POST]
 * @param {void} data The request body based on the OpenAPI specification.
 * @returns {import('@tanstack/react-query').MutationResult<CacheRefreshResponse, unknown, void>}
 */
export const refreshNewsCacheApiV1NewsRefreshPost = (options) => {
  return useMutation({
    mutationFn: (data) => apiClient('post', '/news/api/v1/news/refresh', data),
    ...options,
  });
};

/**
 * @description Hook for /news/api/v1/news/trending [GET]
 * @returns {import('@tanstack/react-query').QueryResult<NewsResponse>}
 */
export const getTrendingNewsApiV1NewsTrendingGet = (options) => {
  const queryKey = ['get_trending_news_api_v1_news_trending_get'];
  return useQuery({
    queryKey,
    queryFn: () => apiClient('get', '/news/api/v1/news/trending'),
    ...options,
  });
};

/**
 * @description Hook for /news/api/v1/news/proxy/image [GET]
 * @returns {import('@tanstack/react-query').QueryResult<object>}
 */
export const proxyImageApiV1NewsProxyImageGet = (options) => {
  const queryKey = ['proxy_image_api_v1_news_proxy_image_get'];
  return useQuery({
    queryKey,
    queryFn: () => apiClient('get', '/news/api/v1/news/proxy/image'),
    ...options,
  });
};

/**
 * @description Hook for /news/ [GET]
 * @returns {import('@tanstack/react-query').QueryResult<RootModel>}
 */
export const newsRoot_Get = (options) => {
  const queryKey = ['news_root__get'];
  return useQuery({
    queryKey,
    queryFn: () => apiClient('get', '/news/'),
    ...options,
  });
};

/**
 * @description Hook for /news/health [GET]
 * @returns {import('@tanstack/react-query').QueryResult<HealthModel>}
 */
export const newsHealthCheckHealthGet = (options) => {
  const queryKey = ['news_health_check_health_get'];
  return useQuery({
    queryKey,
    queryFn: () => apiClient('get', '/news/health'),
    ...options,
  });
};

/**
 * @description Hook for /news/healthz [GET]
 * @returns {import('@tanstack/react-query').QueryResult<HealthZModel>}
 */
export const newsHealthzHealthzGet = (options) => {
  const queryKey = ['news_healthz_healthz_get'];
  return useQuery({
    queryKey,
    queryFn: () => apiClient('get', '/news/healthz'),
    ...options,
  });
};
